#!/usr/bin/env bash
# Hardens a VPS to reduce server-side signals that anonymity/VPN-detection
# checks (e.g. 2ip.io's "privacy bar") key off of: clock skew, DNS-leak-style
# resolver fingerprints, TTL/hop-count anomalies, ICMP/network stack
# fingerprinting, and stray banners that disclose the box is a proxy host.
#
# IMPORTANT — what this script does NOT and CANNOT fix:
#   - IP/ASN reputation. Datacenter/hosting-provider IP ranges are flagged
#     as "hosting" or "VPN/proxy" by IP-intelligence databases (2ip, ipinfo,
#     MaxMind, etc.) regardless of any in-VM configuration. That's a
#     property of the IP block itself, assigned by the hosting provider.
#     The only fix is a residential/mobile-carrier IP, which this script
#     cannot provide.
#   - Reverse DNS (PTR record). This is configured at the hosting provider
#     level (their DNS, not the VM's), not from inside the VPS.
#   - WebRTC leaks. Those happen client-side, in the browser -- entirely
#     outside the server's control.
#
# What it DOES address, all server-side and legitimately useful regardless
# of any anonymity check: accurate clock (NTP), a non-leaking DNS resolver
# for Xray's own outbound DNS, saner default network hardening (ICMP
# redirects/source routing off, rp_filter on, SYN cookies on), a two-way
# ICMP ping block (the box neither answers pings nor can be used to ping
# out, closing basic host-discovery/liveness-probing and traceroute hop
# reveals), normalized TTL so hop-count doesn't visibly change between the
# WARP-routed and direct-routed outbounds, and stripping the "this is a
# proxy/panel box" banners (already partially done by setup.sh's
# `server_tokens off`; this script covers SSH's banner too).
#
# CLI:
#   --uninstall   Revert the sysctl/DNS/TTL/ICMP changes this script made and exit.

set -euo pipefail

SYSCTL_CONF="/etc/sysctl.d/99-anonymize.conf"
BBR_SYSCTL_CONF="/etc/sysctl.d/98-bbr.conf"
RESOLVED_CONF="/etc/systemd/resolved.conf.d/99-anonymize.conf"
SSHD_BANNER_CONF="/etc/ssh/sshd_config.d/99-no-banner.conf"
IPTABLES_TTL_COMMENT="anonymize-ttl-normalize"
IPTABLES_PING_COMMENT="anonymize-icmp-block"
TARGET_TTL="64"
DNS_RESOLVERS="${DNS_RESOLVERS:-1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com}"
DNS_OVER_TLS_MODE="${DNS_OVER_TLS_MODE:-yes}"
DNSSEC_MODE="${DNSSEC_MODE:-yes}"

die() {
  echo "ERROR: $*" >&2
  exit 1
}

require_root() {
  [[ "${EUID}" -eq 0 ]] || die "Run this script as root."
}

log() {
  echo "[anonymize] $*"
}

# ---------------------------------------------------------------------------
# 1. Clock accuracy (NTP)
# ---------------------------------------------------------------------------
# A clock that's off by more than a few seconds is one of the easier
# server-side anomalies to detect (TLS handshake timestamps, HTTP Date
# headers vs actual time). Doesn't prove "VPN", but a wrong clock is a
# needless extra signal.

harden_ntp() {
  log "Ensuring NTP time sync is enabled..."

  if command -v chronyd >/dev/null 2>&1 || command -v chronyc >/dev/null 2>&1; then
    systemctl enable --now chrony >/dev/null 2>&1 ||
      systemctl enable --now chronyd >/dev/null 2>&1 || true
  elif command -v timedatectl >/dev/null 2>&1; then
    timedatectl set-ntp true >/dev/null 2>&1 || true
  else
    apt-get install -y chrony >&2 || die "Failed to install chrony for NTP sync."
    systemctl enable --now chrony >/dev/null 2>&1 || true
  fi

  log "Clock sync status:"
  timedatectl status 2>/dev/null | grep -i "sync\|ntp" >&2 || true
}

unharden_ntp() {
  # Leave NTP enabled -- disabling time sync is never desirable. No-op.
  :
}

# ---------------------------------------------------------------------------
# 2. DNS resolver hardening for Xray's own outbound DNS
# ---------------------------------------------------------------------------
# If Xray (or the OS resolver it inherits) leaks DNS queries to the VPS
# datacenter's default resolver, that resolver's PTR/network range is
# itself an additional hosting-provider signal, and query patterns can
# reveal the box is proxying third-party traffic. Point outbound DNS at a
# resolver that doesn't tie back to the datacenter, and prefer DoT so
# queries aren't plaintext on the wire either. The resolver set is
# configurable via DNS_RESOLVERS rather than hardcoded.

harden_dns() {
  log "Configuring system resolver..."

  if command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files systemd-resolved.service >/dev/null 2>&1; then
    install -d -m 755 "$(dirname -- "$RESOLVED_CONF")"
    cat > "$RESOLVED_CONF" <<EOF
# Generated by anonymize.sh
[Resolve]
DNS=${DNS_RESOLVERS}
DNSOverTLS=${DNS_OVER_TLS_MODE}
DNSSEC=${DNSSEC_MODE}
EOF
    systemctl restart systemd-resolved >/dev/null 2>&1 || true
    log "systemd-resolved configured: DNS='${DNS_RESOLVERS}' DNSOverTLS='${DNS_OVER_TLS_MODE}' DNSSEC='${DNSSEC_MODE}'."
  else
    log "systemd-resolved not present; leaving /etc/resolv.conf untouched (edit manually if needed)."
  fi
}

unharden_dns() {
  if [[ -f "$RESOLVED_CONF" ]]; then
    rm -f "$RESOLVED_CONF"
    systemctl restart systemd-resolved >/dev/null 2>&1 || true
    log "Reverted resolver configuration."
  fi
}

# ---------------------------------------------------------------------------
# 3. Network stack hardening (sysctl)
# ---------------------------------------------------------------------------
# Standard hardening that also closes a few minor fingerprinting/leak
# vectors: ICMP redirects and source-routed packets can be used to probe
# or reroute traffic; reverse-path filtering and SYN cookies are baseline
# good practice for any internet-facing box, proxy or not.

harden_sysctl() {
  log "Applying sysctl network hardening..."

  cat > "$SYSCTL_CONF" <<EOF
# Generated by anonymize.sh
# Ignore ICMP redirects (prevents traffic being silently rerouted)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Don't send ICMP redirects (this is a server, not a router)
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Ignore source-routed packets
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Reverse path filtering (anti-spoofing)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# SYN flood protection
net.ipv4.tcp_syncookies = 1

# Don't respond to ICMP broadcast probes (reduces network-scan fingerprint)
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Don't reply to ICMP echo (ping) at all -- belt-and-suspenders alongside
# the iptables two-way block below.
net.ipv4.icmp_echo_ignore_all = 1

# Ignore bogus ICMP error responses
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Normalized default TTL (matches the iptables TTL rule below; keeps
# locally-originated packets consistent with proxied ones)
net.ipv4.ip_default_ttl = ${TARGET_TTL}
EOF

  sysctl -p "$SYSCTL_CONF" >&2 || die "Failed to apply sysctl settings."
  log "Sysctl hardening applied."
}

unharden_sysctl() {
  if [[ -f "$SYSCTL_CONF" ]]; then
    rm -f "$SYSCTL_CONF"
    log "Removed sysctl hardening config. Reboot (or reload defaults) to fully revert."
  fi
}

# ---------------------------------------------------------------------------
# 4. Two-way ICMP ping block
# ---------------------------------------------------------------------------
# Answering ICMP echo (ping) makes the box trivially discoverable/probeable
# (liveness checks, traceroute hop identification, latency-based relay
# detection). Blocking it two-way means: the box doesn't reply to pings
# aimed at it (INPUT), and nothing running on the box can originate a ping
# either (OUTPUT) -- so an outbound ICMP probe can't be used to fingerprint
# routing/hop count from the server side. Belt-and-suspenders: sysctl
# icmp_echo_ignore_all handles the "don't reply" half at the kernel level;
# the iptables rules below make both directions explicit and are what
# --uninstall actually reverts (sysctl icmp_echo_ignore_all is folded into
# harden_sysctl/unharden_sysctl's single config file already).

harden_ping_block() {
  log "Blocking ICMP echo (ping) two-way..."

  command -v iptables >/dev/null 2>&1 || {
    log "iptables not found, skipping ICMP ping block."
    return
  }

  local chain
  for chain in INPUT OUTPUT; do
    while iptables -C "$chain" -p icmp --icmp-type echo-request -j DROP -m comment --comment "$IPTABLES_PING_COMMENT" 2>/dev/null || \
          iptables -C "$chain" -p icmp --icmp-type echo-reply -j DROP -m comment --comment "$IPTABLES_PING_COMMENT" 2>/dev/null; do
      iptables -D "$chain" -p icmp --icmp-type echo-request -j DROP -m comment --comment "$IPTABLES_PING_COMMENT" 2>/dev/null || true
      iptables -D "$chain" -p icmp --icmp-type echo-reply -j DROP -m comment --comment "$IPTABLES_PING_COMMENT" 2>/dev/null || true
    done
  done

  # INPUT: drop incoming echo-request (don't answer pings aimed at us)
  iptables -A INPUT -p icmp --icmp-type echo-request -j DROP -m comment --comment "$IPTABLES_PING_COMMENT" ||
    log "WARNING: failed to add INPUT ICMP echo-request drop rule."
  # OUTPUT: drop outgoing echo-request (nothing on the box can ping out)
  iptables -A OUTPUT -p icmp --icmp-type echo-request -j DROP -m comment --comment "$IPTABLES_PING_COMMENT" ||
    log "WARNING: failed to add OUTPUT ICMP echo-request drop rule."

  if command -v netfilter-persistent >/dev/null 2>&1; then
    netfilter-persistent save >/dev/null 2>&1 || true
  elif [[ -d /etc/iptables ]]; then
    iptables-save > /etc/iptables/rules.v4 2>/dev/null || true
  fi

  log "Two-way ICMP ping block applied."
}

unharden_ping_block() {
  command -v iptables >/dev/null 2>&1 || return
  local chain
  for chain in INPUT OUTPUT; do
    while iptables -C "$chain" -p icmp --icmp-type echo-request -j DROP -m comment --comment "$IPTABLES_PING_COMMENT" 2>/dev/null; do
      iptables -D "$chain" -p icmp --icmp-type echo-request -j DROP -m comment --comment "$IPTABLES_PING_COMMENT"
    done
  done
  if command -v netfilter-persistent >/dev/null 2>&1; then
    netfilter-persistent save >/dev/null 2>&1 || true
  fi
  log "Removed ICMP ping block rules."
}

# ---------------------------------------------------------------------------
# 5. TTL normalization (hop-count fingerprint)
# ---------------------------------------------------------------------------
# Traffic that hops through an extra tunnel (e.g. the WARP-routed vs
# direct-routed outbounds this proxy uses) can arrive with a different TTL
# than traffic from a "normal" single-hop server, which is a known VPN/relay
# heuristic. Rewriting all outgoing TTLs to a single fixed value removes
# that inconsistency between routing paths.

harden_ttl() {
  log "Normalizing outbound TTL to ${TARGET_TTL} via iptables..."

  command -v iptables >/dev/null 2>&1 || {
    log "iptables not found, skipping TTL normalization."
    return
  }

  # Idempotent: remove any prior rule with our comment before adding.
  while iptables -t mangle -C POSTROUTING -j TTL --ttl-set "$TARGET_TTL" -m comment --comment "$IPTABLES_TTL_COMMENT" 2>/dev/null; do
    iptables -t mangle -D POSTROUTING -j TTL --ttl-set "$TARGET_TTL" -m comment --comment "$IPTABLES_TTL_COMMENT"
  done

  if ! iptables -t mangle -C POSTROUTING -j TTL --ttl-set "$TARGET_TTL" -m comment --comment "$IPTABLES_TTL_COMMENT" 2>/dev/null; then
    iptables -t mangle -A POSTROUTING -j TTL --ttl-set "$TARGET_TTL" -m comment --comment "$IPTABLES_TTL_COMMENT" ||
      log "WARNING: failed to add TTL rule (xt_TTL module may be missing; apt install iptables-persistent may help)."
  fi

  # Persist across reboots if iptables-persistent/netfilter-persistent is present.
  if command -v netfilter-persistent >/dev/null 2>&1; then
    netfilter-persistent save >/dev/null 2>&1 || true
  elif [[ -d /etc/iptables ]]; then
    iptables-save > /etc/iptables/rules.v4 2>/dev/null || true
  fi

  log "TTL normalization applied (best-effort persistence)."
}

unharden_ttl() {
  command -v iptables >/dev/null 2>&1 || return
  while iptables -t mangle -C POSTROUTING -j TTL --ttl-set "$TARGET_TTL" -m comment --comment "$IPTABLES_TTL_COMMENT" 2>/dev/null; do
    iptables -t mangle -D POSTROUTING -j TTL --ttl-set "$TARGET_TTL" -m comment --comment "$IPTABLES_TTL_COMMENT"
  done
  if command -v netfilter-persistent >/dev/null 2>&1; then
    netfilter-persistent save >/dev/null 2>&1 || true
  fi
  log "Removed TTL normalization rule."
}

# ---------------------------------------------------------------------------
# 6. Strip identifying banners
# ---------------------------------------------------------------------------
# nginx's server_tokens is already handled by install.sh. This covers SSH,
# which by default announces its OpenSSH version -- fine for a random VPS,
# but an extra fingerprint bit that costs nothing to remove.

harden_banners() {
  log "Suppressing SSH pre-auth banner..."
  install -d -m 755 "$(dirname -- "$SSHD_BANNER_CONF")"
  cat > "$SSHD_BANNER_CONF" <<'EOF'
# Generated by anonymize.sh
Banner none
DebianBanner no
EOF
  systemctl reload sshd >/dev/null 2>&1 || systemctl reload ssh >/dev/null 2>&1 || true
}

unharden_banners() {
  if [[ -f "$SSHD_BANNER_CONF" ]]; then
    rm -f "$SSHD_BANNER_CONF"
    systemctl reload sshd >/dev/null 2>&1 || systemctl reload ssh >/dev/null 2>&1 || true
  fi
}

# ---------------------------------------------------------------------------
# 7. BBR congestion control (throughput, not anonymity)
# ---------------------------------------------------------------------------
# Unrelated to detection-avoidance -- this is a pure throughput win. BBR
# handles loss/high-latency links (common on international Xray/WARP
# routes) far better than the default cubic congestion control: it doesn't
# back off on non-congestion loss the way loss-based algorithms do, and
# paces sends instead of bursting. Requires `fq` as the default queueing
# discipline for BBR's pacing to actually take effect -- BBR without `fq`
# still runs, but loses its main advantage.
# Kept in its own sysctl file (not harden_sysctl's) and its own
# enable/disable functions since it's a distinct concern from anonymity
# hardening, even though it lives in the same script for convenience.

enable_bbr() {
  log "Enabling BBR congestion control..."

  if ! modprobe tcp_bbr >/dev/null 2>&1; then
    log "WARNING: could not load the tcp_bbr kernel module (unsupported kernel?); skipping BBR."
    return
  fi

  cat > "$BBR_SYSCTL_CONF" <<'EOF'
# Generated by anonymize.sh
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
EOF

  if ! sysctl -p "$BBR_SYSCTL_CONF" >&2; then
    log "WARNING: failed to apply BBR sysctl settings."
    return
  fi

  local active
  active="$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo unknown)"
  if [[ "$active" == "bbr" ]]; then
    log "BBR enabled (active congestion control: ${active})."
  else
    log "WARNING: BBR sysctl applied but active congestion control is '${active}', not bbr."
  fi
}

disable_bbr() {
  if [[ -f "$BBR_SYSCTL_CONF" ]]; then
    rm -f "$BBR_SYSCTL_CONF"
    # Revert to the kernel default (cubic on virtually every distro) rather
    # than just leaving bbr active until next reboot.
    sysctl -w net.ipv4.tcp_congestion_control=cubic >/dev/null 2>&1 || true
    sysctl -w net.core.default_qdisc=pfifo_fast >/dev/null 2>&1 || true
    log "Removed BBR config, reverted to cubic/pfifo_fast."
  fi
}

print_limitations() {
  echo
  echo "=== Limitations (cannot be fixed from inside the VPS) ==="
  echo "  - IP/ASN reputation: your VPS provider's IP range is very likely"
  echo "    tagged 'hosting'/'datacenter' by IP-intelligence databases"
  echo "    (2ip, ipinfo.io, MaxMind, etc.), independent of any config here."
  echo "    Only a residential/mobile IP avoids this, which no script can"
  echo "    grant you on a VPS."
  echo "  - Reverse DNS (PTR record): set via your hosting provider's"
  echo "    control panel/API, not from inside the VM."
  echo "  - WebRTC leaks: entirely client-side (browser), out of server scope."
  echo
  echo "What was hardened: NTP clock sync, Xray/system DNS resolver (DoT,"
  echo "non-datacenter resolver), sysctl network stack hardening, two-way"
  echo "ICMP ping block, outbound TTL normalization, and SSH banner"
  echo "suppression. Also enabled: BBR congestion control (throughput, not"
  echo "an anonymity measure)."
}

uninstall_all() {
  require_root
  echo "=== Reverting VPS anonymization ==="
  unharden_banners
  unharden_ttl
  unharden_ping_block
  unharden_sysctl
  unharden_dns
  unharden_ntp
  disable_bbr
  echo "Done."
}

main() {
  if [[ "${1:-}" == "--uninstall" ]]; then
    uninstall_all
    return
  fi

  require_root

  echo "=== Anonymizing VPS against anonymity/VPN-detection signals ==="
  harden_ntp
  harden_dns
  harden_sysctl
  harden_ping_block
  harden_ttl
  harden_banners
  enable_bbr
  print_limitations

  echo
  echo "Done."
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
