#!/usr/bin/env bash
set -euo pipefail

BASE_DOMAIN=""
PANEL_SUBDOMAIN="admin"
VLESS_SUBDOMAIN="vpn"
PANEL_PATH=""
EMAIL=""
PANEL_PORT=""
SUB_PORT=""
WS_PORT=""
GRPC_PORT=""
XHTTP_PORT=""

WS_PATH=""
GRPC_SERVICE=""
XHTTP_PATH=""
SUB_PATH=""

# Optional source file for the default public fallback page on the VLESS hostname.
# When unset, non-proxy requests deliberately retain the 404 response.
FALLBACK_HTML_PATH="${FALLBACK_HTML_PATH:-}"

CERT_DIR=""
CF_CREDENTIALS="/etc/letsencrypt/cloudflare.ini"

CLIENT_UUID=""
CLIENT_SUB_ID=""
VPS_FLAG=""
# Optional ISO 3166-1 alpha-2 country code for inbound labels. When unset,
# the code is detected from the server's public IP.
VPS_COUNTRY_CODE="${VPS_COUNTRY_CODE:-}"
XUI_USERNAME=""
XUI_PASSWORD=""

NGINX_SITE="/etc/nginx/sites-available/3xui-proxy"
NGINX_SITE_ENABLED="/etc/nginx/sites-enabled/3xui-proxy"
FALLBACK_HTML_DEST="/etc/nginx/3xui-proxy-fallback.html"

CF_REAL_IP_CONF="/etc/nginx/conf.d/cloudflare-real-ip.conf"
CF_IP_STATE_FILE="/etc/nginx/.3xui-proxy-cloudflare-ips.state"
CERTBOT_DEPLOY_HOOK="/etc/letsencrypt/renewal-hooks/deploy/nginx-reload.sh"

STATE_FILE="/etc/nginx/.3xui-proxy-ports.state"
CONFIG_FILE="/etc/nginx/.3xui-proxy.conf"

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"

TMP_FILES=()
CF_IP_RANGES=()

die() {
  echo "ERROR: $*" >&2
  exit 1
}

cleanup_tmp_files() {
  local f
  # NOTE: bare `[[ ... ]] && cmd` here would abort the whole script under
  # `set -e` whenever the condition is false (e.g. TMP_FILES is empty) --
  # an AND-list's exit status is that of its last evaluated command, and
  # this runs as an EXIT trap, so that false exit status becomes the
  # process's exit code. Use an explicit if instead.
  for f in "${TMP_FILES[@]:-}"; do
    if [[ -n "$f" && -e "$f" ]]; then
      rm -f "$f"
    fi
  done
}

trap cleanup_tmp_files EXIT

make_tmp_file() {
  local f
  f="$(mktemp)"
  TMP_FILES+=("$f")
  printf '%s\n' "$f"
}

require_root() {
  [[ "${EUID}" -eq 0 ]] || die "Run this script as root."
}

load_config() {
  if [[ -f "$CONFIG_FILE" ]]; then
    echo "Loading saved configuration from ${CONFIG_FILE}..."
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
  fi
}

save_config() {
  install -d -m 755 "$(dirname -- "$CONFIG_FILE")"
  cat > "$CONFIG_FILE" <<EOF
# Generated by setup.sh on ${TIMESTAMP}
BASE_DOMAIN="${BASE_DOMAIN}"
PANEL_SUBDOMAIN="${PANEL_SUBDOMAIN}"
VLESS_SUBDOMAIN="${VLESS_SUBDOMAIN}"
PANEL_PATH="${PANEL_PATH}"
EMAIL="${EMAIL}"
PANEL_PORT="${PANEL_PORT}"
SUB_PORT="${SUB_PORT}"
WS_PORT="${WS_PORT}"
GRPC_PORT="${GRPC_PORT}"
XHTTP_PORT="${XHTTP_PORT}"
WS_PATH="${WS_PATH}"
GRPC_SERVICE="${GRPC_SERVICE}"
XHTTP_PATH="${XHTTP_PATH}"
SUB_PATH="${SUB_PATH}"
CLIENT_UUID="${CLIENT_UUID}"
CLIENT_SUB_ID="${CLIENT_SUB_ID}"
VPS_COUNTRY_CODE="${VPS_COUNTRY_CODE}"
EOF
  chmod 600 "$CONFIG_FILE"
}

prompt() {
  local variable_name="$1"
  local prompt_text="$2"
  local default_value="${3:-}"
  local value=""

  if [[ -n "$default_value" ]]; then
    read -r -p "${prompt_text} [${default_value}]: " value
    value="${value:-$default_value}"
  else
    while true; do
      read -r -p "${prompt_text}: " value

      if [[ -n "$value" ]]; then
        break
      fi

      echo "Value is required."
    done
  fi

  printf -v "$variable_name" '%s' "$value"
}

prompt_secret() {
  local variable_name="$1"
  local prompt_text="$2"
  local value=""

  while true; do
    read -r -s -p "${prompt_text}: " value
    echo

    if [[ -n "$value" ]]; then
      break
    fi

    echo "Value is required."
  done

  printf -v "$variable_name" '%s' "$value"
}

validate_port() {
  local port_name="$1"
  local port="$2"

  [[ "$port" =~ ^[0-9]+$ ]] ||
    die "${port_name} must be a number."

  ((port >= 1 && port <= 65535)) ||
    die "${port_name} must be between 1 and 65535."
}

port_is_listening() {
  local port="$1"

  ss -H -ltn "sport = :${port}" 2>/dev/null | grep -q .
}

random_free_port() {
  # Accepts any number of ports to exclude (in addition to "already listening").
  # Deliberately iterates "$@" directly rather than building a local array:
  # under `set -u`, expanding an EMPTY array (i.e. called with zero args) as
  # "${arr[@]}" throws "unbound variable" on bash < 4.4 (e.g. macOS's
  # bundled /bin/bash), which random_free_port (no args) relies on.
  local port=""
  local excluded
  local collision

  while true; do
    port="$(od -An -N2 -tu2 /dev/urandom | tr -d ' ')"
    port=$((49152 + port % 16384))

    collision=false
    for excluded in "$@"; do
      [[ -n "$excluded" && "$port" == "$excluded" ]] && { collision=true; break; }
    done
    [[ "$collision" == false ]] || continue

    if ! port_is_listening "$port"; then
      printf '%s\n' "$port"
      return
    fi
  done
}

normalize_panel_path() {
  PANEL_PATH="/${PANEL_PATH#/}"

  while [[ "$PANEL_PATH" != "/" && "$PANEL_PATH" == */ ]]; do
    PANEL_PATH="${PANEL_PATH%/}"
  done

  [[ "$PANEL_PATH" != "/" ]] ||
    die "Panel path cannot be /."

  [[ "$PANEL_PATH" =~ ^/[A-Za-z0-9/_-]*$ ]] ||
    die "Panel path may only contain letters, numbers, '/', '_' and '-'."
}

normalize_ws_path() {
  WS_PATH="/${WS_PATH#/}"

  while [[ "$WS_PATH" != "/" && "$WS_PATH" == */ ]]; do
    WS_PATH="${WS_PATH%/}"
  done

  [[ "$WS_PATH" != "/" ]] ||
    die "WebSocket path cannot be /."

  [[ "$WS_PATH" =~ ^/[A-Za-z0-9/_-]*$ ]] ||
    die "WebSocket path may only contain letters, numbers, '/', '_' and '-'."
}

normalize_xhttp_path() {
  XHTTP_PATH="/${XHTTP_PATH#/}"

  while [[ "$XHTTP_PATH" != "/" && "$XHTTP_PATH" == */ ]]; do
    XHTTP_PATH="${XHTTP_PATH%/}"
  done

  [[ "$XHTTP_PATH" != "/" ]] ||
    die "XHTTP path cannot be /."

  [[ "$XHTTP_PATH" =~ ^/[A-Za-z0-9/_-]*$ ]] ||
    die "XHTTP path may only contain letters, numbers, '/', '_' and '-'."
}

normalize_sub_path() {
  SUB_PATH="/${SUB_PATH#/}"

  while [[ "$SUB_PATH" != "/" && "$SUB_PATH" == */ ]]; do
    SUB_PATH="${SUB_PATH%/}"
  done

  [[ "$SUB_PATH" != "/" ]] ||
    die "Subscription path cannot be /."

  [[ "$SUB_PATH" =~ ^/[A-Za-z0-9/_-]*$ ]] ||
    die "Subscription path may only contain letters, numbers, '/', '_' and '-'."
}

validate_inputs() {
  [[ "$BASE_DOMAIN" =~ ^([A-Za-z0-9-]+\.)+[A-Za-z]{2,}$ ]] ||
    die "Invalid base domain."

  [[ "$PANEL_SUBDOMAIN" =~ ^[A-Za-z0-9-]+$ ]] ||
    die "Invalid panel subdomain."

  [[ "$VLESS_SUBDOMAIN" =~ ^[A-Za-z0-9-]+$ ]] ||
    die "Invalid VLESS subdomain."

  [[ "$PANEL_SUBDOMAIN" != "$VLESS_SUBDOMAIN" ]] ||
    die "Panel and VLESS subdomains must be different."

  [[ "$EMAIL" =~ ^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$ ]] ||
    die "Invalid email address."

  [[ "$GRPC_SERVICE" =~ ^[A-Za-z0-9._-]+$ ]] ||
    die "Invalid gRPC service name."

  validate_port "Subscription port" "$SUB_PORT"
  validate_port "WebSocket port" "$WS_PORT"
  validate_port "gRPC port" "$GRPC_PORT"
  validate_port "XHTTP port" "$XHTTP_PORT"

  [[ "$SUB_PORT" != "$WS_PORT" ]] ||
    die "Subscription and WebSocket ports must be different."

  [[ "$SUB_PORT" != "$GRPC_PORT" ]] ||
    die "Subscription and gRPC ports must be different."

  [[ "$WS_PORT" != "$GRPC_PORT" ]] ||
    die "WebSocket and gRPC ports must be different."

  local other_port
  for other_port in "$SUB_PORT" "$WS_PORT" "$GRPC_PORT"; do
    [[ "$XHTTP_PORT" != "$other_port" ]] ||
      die "XHTTP port must be different from every other internal port."
  done

  local internal_port
  local internal_port_name
  for internal_port_name_port in \
    "Subscription port:$SUB_PORT" \
    "WebSocket port:$WS_PORT" \
    "gRPC port:$GRPC_PORT" \
    "XHTTP port:$XHTTP_PORT"
  do
    internal_port_name="${internal_port_name_port%%:*}"
    internal_port="${internal_port_name_port#*:}"

    [[ "$internal_port" != "443" ]] ||
      die "${internal_port_name} cannot be 443 (reserved for the public HTTPS listener)."
  done

  normalize_ws_path
  normalize_xhttp_path
  normalize_sub_path
}

# Called once PANEL_PATH is known (after 3x-ui install). PANEL_PORT itself is
# pre-reserved by collect_input() BEFORE 3x-ui is installed (see there), and
# explicitly handed to the installer -- so it should always come back
# unchanged. This is a defensive re-check only, in case an already-installed
# 3x-ui (found already configured, so our reservation was ignored) reports
# back a conflicting port.
validate_panel_port() {
  validate_port "Panel port" "$PANEL_PORT"

  [[ "$PANEL_PORT" != "443" ]] ||
    die "3x-ui panel port is 443, reserved for the public HTTPS listener. Change it via 'x-ui setting -port <port>' on the server, then re-run this script."

  [[ "$PANEL_PORT" != "$WS_PORT" ]] ||
    die "3x-ui panel port ${PANEL_PORT} collides with WS_PORT. Change it via 'x-ui setting -port <port>' on the server, then re-run this script."

  [[ "$PANEL_PORT" != "$GRPC_PORT" ]] ||
    die "3x-ui panel port ${PANEL_PORT} collides with GRPC_PORT. Change it via 'x-ui setting -port <port>' on the server, then re-run this script."

  [[ "$PANEL_PORT" != "$XHTTP_PORT" ]] ||
    die "3x-ui panel port ${PANEL_PORT} collides with XHTTP_PORT. Change it via 'x-ui setting -port <port>' on the server, then re-run this script."

  [[ "$PANEL_PORT" != "$SUB_PORT" ]] ||
    die "3x-ui panel port ${PANEL_PORT} collides with SUB_PORT. Change it via 'x-ui setting -port <port>' on the server, then re-run this script."

  normalize_panel_path
}

collect_input() {
  local default_ws_port=""
  local default_grpc_port=""
  local default_xhttp_port=""

  echo
  echo "=== VLESS + Nginx Setup ==="
  echo

  prompt BASE_DOMAIN "Base domain, for example example.com" "$BASE_DOMAIN"
  prompt PANEL_SUBDOMAIN "Panel subdomain" "$PANEL_SUBDOMAIN"
  prompt VLESS_SUBDOMAIN "VLESS subdomain" "$VLESS_SUBDOMAIN"
  prompt EMAIL "Let's Encrypt email" "$EMAIL"

  echo
  echo "All internal ports and paths are generated automatically (random, unique,"
  echo "collision-free). Panel credentials and web base path are generated by the"
  echo "3x-ui installer itself. Nothing else to configure — just confirm below."

  SUB_PORT="${SUB_PORT:-$(random_free_port "443")}"
  validate_port "Subscription port" "$SUB_PORT"

  default_ws_port="${WS_PORT:-$(random_free_port "$SUB_PORT")}"
  default_grpc_port="${GRPC_PORT:-$(random_free_port "$SUB_PORT" "$default_ws_port")}"
  default_xhttp_port="${XHTTP_PORT:-$(random_free_port "$SUB_PORT" "$default_ws_port" "$default_grpc_port")}"

  prompt WS_PORT "WebSocket local port" "$default_ws_port"
  validate_port "WebSocket port" "$WS_PORT"

  if port_is_listening "$WS_PORT"; then
    echo "WARNING: port ${WS_PORT} is already in use by another process on this host." >&2
  fi

  prompt GRPC_PORT "gRPC local port" "$default_grpc_port"
  validate_port "gRPC port" "$GRPC_PORT"

  if port_is_listening "$GRPC_PORT"; then
    echo "WARNING: port ${GRPC_PORT} is already in use by another process on this host." >&2
  fi

  prompt XHTTP_PORT "XHTTP local port" "$default_xhttp_port"
  validate_port "XHTTP port" "$XHTTP_PORT"

  if port_is_listening "$XHTTP_PORT"; then
    echo "WARNING: port ${XHTTP_PORT} is already in use by another process on this host." >&2
  fi

  # Reserve the panel port here too, BEFORE 3x-ui is installed, so it cannot
  # collide with any port already claimed above. Reused as-is on reruns
  # (loaded from CONFIG_FILE by load_config) so it stays stable.
  PANEL_PORT="${PANEL_PORT:-$(random_free_port "443" "$SUB_PORT" "$WS_PORT" "$GRPC_PORT" "$XHTTP_PORT")}"
  validate_port "Panel port" "$PANEL_PORT"

  if port_is_listening "$PANEL_PORT"; then
    echo "WARNING: port ${PANEL_PORT} is already in use by another process on this host." >&2
  fi

  echo
  # Auto-generate WS_PATH, XHTTP_PATH, GRPC_SERVICE, and SUB_PATH if not already set
  # (loaded from CONFIG_FILE on reruns). These are security-sensitive but
  # must look like plausible real API endpoints to avoid standing out.
  if [[ -z "$WS_PATH" ]]; then
    local ws_words=(events stream messages notifications updates sync relay)
    WS_PATH="/api/v$(( RANDOM % 3 + 1 ))/${ws_words[RANDOM % ${#ws_words[@]}]}/$(openssl rand -hex 4)"
  fi
  if [[ -z "$XHTTP_PATH" ]]; then
    local xhttp_words=(telemetry ingest batch gateway upload)
    XHTTP_PATH="/api/v$(( RANDOM % 3 + 1 ))/${xhttp_words[RANDOM % ${#xhttp_words[@]}]}/$(openssl rand -hex 4)"
  fi
  if [[ -z "$GRPC_SERVICE" ]]; then
    local grpc_orgs=(internal backend core cloud platform service)
    local grpc_pkgs=(sync relay push telemetry health streaming)
    local grpc_svcs=(SyncService RelayService PushService EventService DataService StreamService)
    GRPC_SERVICE="com.${grpc_orgs[RANDOM % ${#grpc_orgs[@]}]}.${grpc_pkgs[RANDOM % ${#grpc_pkgs[@]}]}.v$(( RANDOM % 3 + 1 )).${grpc_svcs[RANDOM % ${#grpc_svcs[@]}]}"
  fi
  if [[ -z "$SUB_PATH" ]]; then
    local sub_words=(download resources assets static content files docs)
    SUB_PATH="/${sub_words[RANDOM % ${#sub_words[@]}]}/$(openssl rand -hex 6)"
  fi

  if [[ -z "${CLOUDFLARE_API_TOKEN:-}" ]]; then
    echo
    prompt_secret CLOUDFLARE_API_TOKEN "Cloudflare API Token"
  fi

  validate_inputs
}

confirm_configuration() {
  local panel_domain="${PANEL_SUBDOMAIN}.${BASE_DOMAIN}"
  local vless_domain="${VLESS_SUBDOMAIN}.${BASE_DOMAIN}"
  local answer=""

  echo
  echo "Configuration"
  echo
  echo "Base domain: ${BASE_DOMAIN}"
  echo
  echo "Panel:"
  echo "  domain: ${panel_domain}"
  echo "  public/client port: 443"
  echo "  internal 3x-ui port: ${PANEL_PORT:-<auto-generated by 3x-ui installer>}"
  echo "  path: ${PANEL_PATH:-<auto-generated by 3x-ui installer>}"
  echo
  echo "VLESS WebSocket:"
  echo "  domain: ${vless_domain}"
  echo "  public/client port: 443"
  echo "  internal Xray port: ${WS_PORT}"
  echo "  path: ${WS_PATH}"
  echo
  echo "VLESS XHTTP:"
  echo "  domain: ${vless_domain}"
  echo "  public/client port: 443"
  echo "  internal Xray port: ${XHTTP_PORT}"
  echo "  network: xhttp (packet-up)"
  echo "  path: ${XHTTP_PATH}"
  echo
  echo "VLESS gRPC:"
  echo "  domain: ${vless_domain}"
  echo "  public/client port: 443"
  echo "  internal Xray port: ${GRPC_PORT}"
  echo "  serviceName: ${GRPC_SERVICE}"
  echo
  echo "Subscription:"
  echo "  URL: https://${panel_domain}${SUB_PATH}/"
  echo "  internal port: ${SUB_PORT}"
  echo
  echo "Firewall:"
  echo "  allowed: 443/tcp from Cloudflare IP ranges only (SSH is left untouched by this script)"
  echo "  denied: public 443/tcp, 80/tcp, ${PANEL_PORT}/tcp, ${SUB_PORT}/tcp, ${WS_PORT}/tcp, ${GRPC_PORT}/tcp, ${XHTTP_PORT}/tcp"
  echo

  read -r -p "Continue? [y/N]: " answer

  case "$answer" in
    y|Y|yes|YES)
      ;;
    *)
      echo "Cancelled."
      exit 0
      ;;
  esac
}

install_packages() {
  echo "[1/8] Installing packages..."

  if [[ -d /etc/needrestart/conf.d ]]; then
    # shellcheck disable=SC2016
    echo '$nrconf{restart} = '\''a'\'';' > /etc/needrestart/conf.d/50-autorestart.conf
  fi

  apt update

  apt install -y \
    nginx \
    certbot \
    python3-certbot-dns-cloudflare \
    ufw \
    curl \
    ca-certificates \
    openssl \
    python3
}

write_cloudflare_credentials() {
  echo "[2/8] Writing Cloudflare credentials..."

  install -d -m 700 /etc/letsencrypt

  local tmp_cf_credentials
  tmp_cf_credentials="$(make_tmp_file)"

  cat > "$tmp_cf_credentials" <<EOF
dns_cloudflare_api_token = ${CLOUDFLARE_API_TOKEN}
EOF

  chmod 600 "$tmp_cf_credentials"
  mv "$tmp_cf_credentials" "$CF_CREDENTIALS"
}

issue_certificate() {
  echo "[3/8] Issuing or renewing wildcard certificate..."

  certbot certonly \
    --dns-cloudflare \
    --dns-cloudflare-credentials "$CF_CREDENTIALS" \
    --dns-cloudflare-propagation-seconds 30 \
    --cert-name "$BASE_DOMAIN" \
    -d "$BASE_DOMAIN" \
    -d "*.${BASE_DOMAIN}" \
    --email "$EMAIL" \
    --agree-tos \
    --non-interactive \
    --keep-until-expiring
}

install_certbot_hook() {
  echo "[4/8] Installing permanent Certbot deploy hook..."

  install -d -m 755 /etc/letsencrypt/renewal-hooks/deploy

  cat > "$CERTBOT_DEPLOY_HOOK" <<'EOF'
#!/usr/bin/env sh
set -eu

nginx -t
systemctl reload nginx
EOF

  chmod 755 "$CERTBOT_DEPLOY_HOOK"

  systemctl enable certbot.timer >/dev/null 2>&1 || true
  systemctl start certbot.timer >/dev/null 2>&1 || true
}

write_cloudflare_real_ip_config() {
  echo "[5/8] Writing Cloudflare real IP configuration..."

  local tmp_cf_real_ip
  local backup=""
  local cf_ipv4=""
  local cf_ipv6=""

  tmp_cf_real_ip="$(make_tmp_file)"

  cf_ipv4="$(curl -fsSL https://www.cloudflare.com/ips-v4)" ||
    die "Failed to fetch Cloudflare IPv4 ranges. Check network connectivity and retry."

  [[ -n "$cf_ipv4" ]] ||
    die "Cloudflare IPv4 ranges response was empty."

  cf_ipv6="$(curl -fsSL https://www.cloudflare.com/ips-v6)" ||
    die "Failed to fetch Cloudflare IPv6 ranges. Check network connectivity and retry."

  [[ -n "$cf_ipv6" ]] ||
    die "Cloudflare IPv6 ranges response was empty."

  # Reuse the exact ranges fetched for nginx when locking the origin firewall.
  # Do not use mapfile: Debian supports it, but macOS's Bash 3 does not.
  CF_IP_RANGES=()
  while IFS= read -r cf_range; do
    [[ -n "$cf_range" ]] && CF_IP_RANGES+=("$cf_range")
  done < <(printf '%s\n%s\n' "$cf_ipv4" "$cf_ipv6" | sed '/^[[:space:]]*$/d')
  ((${#CF_IP_RANGES[@]} > 0)) || die "No Cloudflare IP ranges were parsed."

  {
    echo "# Generated by setup-vless-nginx.sh"
    echo "# Trust CF-Connecting-IP only from official Cloudflare networks"

    printf '%s\n' "$cf_ipv4" | sed 's/^/set_real_ip_from /; s/$/;/'
    printf '%s\n' "$cf_ipv6" | sed 's/^/set_real_ip_from /; s/$/;/'

    echo "real_ip_header CF-Connecting-IP;"
    echo "real_ip_recursive on;"
  } > "$tmp_cf_real_ip"

  if [[ -e "$CF_REAL_IP_CONF" ]]; then
    backup="${CF_REAL_IP_CONF}.backup-${TIMESTAMP}"
    cp -a "$CF_REAL_IP_CONF" "$backup"
  fi

  mv "$tmp_cf_real_ip" "$CF_REAL_IP_CONF"
  chmod 644 "$CF_REAL_IP_CONF"

  if ! nginx -t; then
    echo "ERROR: Cloudflare real IP configuration is invalid."
    echo "Restoring previous configuration..."

    if [[ -n "$backup" ]]; then
      cp -a "$backup" "$CF_REAL_IP_CONF"
    else
      rm -f "$CF_REAL_IP_CONF"
    fi

    nginx -t || true
    exit 1
  fi
}

nginx_listen_directive() {
  local version=""
  local major=0
  local minor=0
  local patch=0

  version="$(nginx -v 2>&1 | sed -n 's#.*nginx/\([0-9.]*\).*#\1#p')"

  if [[ "$version" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
    major="${BASH_REMATCH[1]}"
    minor="${BASH_REMATCH[2]}"
    patch="${BASH_REMATCH[3]}"
  fi

  # `http2 on;` as a separate directive was introduced in nginx 1.25.1.
  # Older versions only understand the combined `listen ... http2;` form.
  if ((major > 1 || (major == 1 && minor > 25) || (major == 1 && minor == 25 && patch >= 1))); then
    printf '%s\n' "listen 443 ssl;
    http2 on;"
  else
    printf '%s\n' "listen 443 ssl http2;"
  fi
}

check_port_443() {
  local pid=""
  local proc_name=""
  local answer=""

  if ! port_is_listening 443; then
    return
  fi

  pid="$(ss -H -ltnp 'sport = :443' 2>/dev/null | grep -oP 'pid=\K[0-9]+' | head -1)"
  proc_name="$(ps -p "${pid:-0}" -o comm= 2>/dev/null || echo "unknown")"

  # If it's nginx itself, that's fine — we'll reload it.
  if [[ "$proc_name" == "nginx" ]]; then
    return
  fi

  echo
  echo "WARNING: port 443 is already in use by: ${proc_name} (PID ${pid})"
  echo "Nginx needs to bind to port 443. The conflicting process must be stopped."
  echo
  read -r -p "Stop ${proc_name} (PID ${pid}) now? [y/N]: " answer

  case "$answer" in
    y|Y|yes|YES)
      echo "Stopping ${proc_name} (PID ${pid})..."
      kill "$pid" 2>/dev/null || true
      sleep 2

      if port_is_listening 443; then
        echo "Process did not stop gracefully, sending SIGKILL..."
        kill -9 "$pid" 2>/dev/null || true
        sleep 1
      fi

      if port_is_listening 443; then
        die "Port 443 is still in use. Please stop the process manually and re-run."
      fi

      echo "Port 443 is now free."
      ;;
    *)
      die "Cannot proceed while port 443 is occupied by another process."
      ;;
  esac
}

prepare_fallback_page() {
  if [[ -z "$FALLBACK_HTML_PATH" ]]; then
    rm -f "$FALLBACK_HTML_DEST"
    return
  fi

  [[ -f "$FALLBACK_HTML_PATH" && -r "$FALLBACK_HTML_PATH" ]] ||
    die "FALLBACK_HTML_PATH must point to a readable regular file: ${FALLBACK_HTML_PATH}"

  install -m 644 "$FALLBACK_HTML_PATH" "$FALLBACK_HTML_DEST"
}

nginx_vless_fallback_location() {
  if [[ -n "$FALLBACK_HTML_PATH" ]]; then
    cat <<EOF
    location = / {
        root /etc/nginx;
        try_files /3xui-proxy-fallback.html =404;
    }

    location / {
        return 404;
    }
EOF
  else
    cat <<'EOF'
    location / {
        return 404;
    }
EOF
  fi
}

write_nginx_config() {
  echo "[6/8] Writing Nginx reverse proxy configuration..."

  prepare_fallback_page

  check_port_443

  local panel_domain="${PANEL_SUBDOMAIN}.${BASE_DOMAIN}"
  local vless_domain="${VLESS_SUBDOMAIN}.${BASE_DOMAIN}"
  local grpc_location="/${GRPC_SERVICE}"
  local vless_fallback_location
  local tmp_nginx
  local backup=""
  local default_site_was_enabled=false
  local listen_directive

  listen_directive="$(nginx_listen_directive)"
  vless_fallback_location="$(nginx_vless_fallback_location)"

  tmp_nginx="$(make_tmp_file)"

  cat > "$tmp_nginx" <<EOF
map \$http_upgrade \$connection_upgrade {
    default upgrade;
    '' close;
}

limit_req_zone \$binary_remote_addr zone=panel_limit:10m rate=30r/s;

server {
    ${listen_directive}
    server_name ${vless_domain};

    ssl_certificate ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    server_tokens off;

    location = ${WS_PATH} {
        proxy_pass http://127.0.0.1:${WS_PORT};

        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;

        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    # packet-up places the session ID and sequence below XHTTP_PATH, so this
    # must be a prefix location rather than an exact-path match.
    location ^~ ${XHTTP_PATH} {
        # Xray's XHTTP documentation recommends grpc_pass for Nginx/CDN
        # traversal. Cloudflare's gRPC setting must be enabled for this zone.
        grpc_pass grpc://127.0.0.1:${XHTTP_PORT};

        grpc_set_header Host \$host;
        grpc_set_header X-Real-IP \$remote_addr;
        grpc_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto https;

        grpc_read_timeout 600s;
        grpc_send_timeout 600s;
        grpc_socket_keepalive on;

        client_body_buffer_size 512k;
        client_max_body_size 0;
    }

    location ${grpc_location} {
        grpc_pass grpc://127.0.0.1:${GRPC_PORT};

        grpc_set_header Host \$host;
        grpc_set_header X-Real-IP \$remote_addr;
        grpc_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto https;

        grpc_read_timeout 600s;
        grpc_send_timeout 600s;
        grpc_socket_keepalive on;

        client_body_buffer_size 512k;
        client_max_body_size 0;
    }

${vless_fallback_location}
}

server {
    ${listen_directive}
    server_name ${panel_domain};

    ssl_certificate ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    server_tokens off;

    location = ${PANEL_PATH} {
        return 301 ${PANEL_PATH}/;
    }

    location ${PANEL_PATH}/ {
        limit_req zone=panel_limit burst=60 nodelay;

        proxy_pass http://127.0.0.1:${PANEL_PORT};

        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    location ${SUB_PATH}/ {
        proxy_pass http://127.0.0.1:${SUB_PORT};

        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    location / {
        return 404;
    }
}
EOF

  if [[ -e "$NGINX_SITE" ]]; then
    backup="${NGINX_SITE}.backup-${TIMESTAMP}"
    cp -a "$NGINX_SITE" "$backup"
  fi

  if [[ -e /etc/nginx/sites-enabled/default ]]; then
    default_site_was_enabled=true
  fi

  mv "$tmp_nginx" "$NGINX_SITE"
  chmod 644 "$NGINX_SITE"

  ln -sfn "$NGINX_SITE" "$NGINX_SITE_ENABLED"
  rm -f /etc/nginx/sites-enabled/default

  if ! nginx -t; then
    echo "ERROR: New Nginx configuration is invalid."
    echo "Restoring previous configuration..."

    if [[ -n "$backup" ]]; then
      cp -a "$backup" "$NGINX_SITE"
      ln -sfn "$NGINX_SITE" "$NGINX_SITE_ENABLED"
    else
      rm -f "$NGINX_SITE"
      rm -f "$NGINX_SITE_ENABLED"
    fi

    if [[ "$default_site_was_enabled" == true ]]; then
      ln -sfn \
        /etc/nginx/sites-available/default \
        /etc/nginx/sites-enabled/default
    fi

    nginx -t || true
    exit 1
  fi

  systemctl reload nginx || systemctl restart nginx
}

configure_ufw() {
  echo "[7/8] Configuring UFW..."

  # 443/tcp is intentionally open to the whole internet, not just Cloudflare:
  # direct-connection inbounds (VLESS+Reality, NaiveProxy) share port 443 with
  # the Cloudflare-fronted CDN inbounds via Nginx's SNI-based routing, so
  # restricting 443 to Cloudflare's ranges would block those direct clients.
  # Clean up any per-range Cloudflare-only allow rules left over from a
  # previous run of this script (pre-direct-connection-inbound versions).
  local old_cf_range
  if [[ -f "$CF_IP_STATE_FILE" ]]; then
    while IFS= read -r old_cf_range; do
      [[ -n "$old_cf_range" ]] || continue
      ufw delete allow from "$old_cf_range" to any port 443 proto tcp || true
    done < "$CF_IP_STATE_FILE"
    rm -f "$CF_IP_STATE_FILE"
  fi

  local prev_panel_port=""
  local prev_sub_port=""
  local prev_ws_port=""
  local prev_grpc_port=""
  local prev_xhttp_port=""

  if [[ -f "$STATE_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE"
    prev_panel_port="${STATE_PANEL_PORT:-}"
    prev_sub_port="${STATE_SUB_PORT:-}"
    prev_ws_port="${STATE_WS_PORT:-}"
    prev_grpc_port="${STATE_GRPC_PORT:-}"
    prev_xhttp_port="${STATE_XHTTP_PORT:-}"
  fi

  # Remove stale deny rules left over from a previous run with different ports.
  for stale_port in "$prev_panel_port" "$prev_sub_port" "$prev_ws_port" "$prev_grpc_port" "$prev_xhttp_port"; do
    if [[ -n "$stale_port" ]] &&
       [[ "$stale_port" != "$PANEL_PORT" ]] &&
       [[ "$stale_port" != "$SUB_PORT" ]] &&
       [[ "$stale_port" != "$WS_PORT" ]] &&
       [[ "$stale_port" != "$GRPC_PORT" ]] &&
       [[ "$stale_port" != "$XHTTP_PORT" ]]; then
      ufw delete deny "${stale_port}/tcp" || true
    fi
  done

  # Deliberately does NOT touch SSH (allow/deny) at all -- this script only
  # owns the panel/proxy-related ports. Managing the SSH rule here risked a
  # lockout (enabling UFW without an SSH allow rule already in place, or
  # deleting the wrong one on --uninstall) for something entirely unrelated
  # to this script's job. If SSH isn't already reachable through UFW on this
  # host, allow it yourself, e.g.: ufw allow 22/tcp
  # Remove any stale rules before adding the current one (idempotent reruns).
  ufw delete allow 443/tcp || true
  ufw delete deny 443/tcp || true
  ufw allow 443/tcp

  ufw deny 80/tcp || true
  ufw deny "${PANEL_PORT}/tcp" || true
  ufw deny "${SUB_PORT}/tcp" || true
  ufw deny "${WS_PORT}/tcp" || true
  ufw deny "${GRPC_PORT}/tcp" || true
  ufw deny "${XHTTP_PORT}/tcp" || true

  ufw --force enable
  ufw reload

  cat > "$STATE_FILE" <<EOF
STATE_PANEL_PORT=${PANEL_PORT}
STATE_SUB_PORT=${SUB_PORT}
STATE_WS_PORT=${WS_PORT}
STATE_GRPC_PORT=${GRPC_PORT}
STATE_XHTTP_PORT=${XHTTP_PORT}
EOF
  chmod 600 "$STATE_FILE"
}

print_summary() {
  local panel_domain="${PANEL_SUBDOMAIN}.${BASE_DOMAIN}"
  local vless_domain="${VLESS_SUBDOMAIN}.${BASE_DOMAIN}"

  echo "[8/8] Done."
  echo
  echo "Panel:"
  echo "  URL: https://${panel_domain}${PANEL_PATH}/"
  echo "  public/client port: 443"
  echo "  internal 3x-ui port: ${PANEL_PORT}"
  echo
  echo "VLESS WebSocket:"
  echo "  domain: ${vless_domain}"
  echo "  public/client port: 443"
  echo "  internal Xray port: ${WS_PORT}"
  echo "  security: tls"
  echo "  network: ws"
  echo "  path: ${WS_PATH}"
  echo
  echo "VLESS XHTTP:"
  echo "  domain: ${vless_domain}"
  echo "  public/client port: 443"
  echo "  internal Xray port: ${XHTTP_PORT}"
  echo "  security: tls (terminated by Nginx)"
  echo "  network: xhttp"
  echo "  path: ${XHTTP_PATH}"
  echo "  Cloudflare: proxied DNS + gRPC enabled"
  echo
  echo "VLESS gRPC:"
  echo "  domain: ${vless_domain}"
  echo "  public/client port: 443"
  echo "  internal Xray port: ${GRPC_PORT}"
  echo "  security: tls"
  echo "  network: grpc"
  echo "  serviceName: ${GRPC_SERVICE}"
  echo
  echo "Subscription:"
  echo "  URL: https://${panel_domain}${SUB_PATH}/"
  echo "  internal port: ${SUB_PORT}"
  echo
  echo "UFW:"
  echo "  allowed: 443/tcp from Cloudflare IP ranges only (SSH is left untouched by this script)"
  echo "  denied: public 443/tcp, 80/tcp, ${PANEL_PORT}/tcp, ${SUB_PORT}/tcp, ${WS_PORT}/tcp, ${GRPC_PORT}/tcp, ${XHTTP_PORT}/tcp"
  echo
  echo "Files:"
  echo "  Nginx site: ${NGINX_SITE}"
  echo "  Cloudflare real IP config: ${CF_REAL_IP_CONF}"
  echo "  Cloudflare credentials: ${CF_CREDENTIALS}"
  echo "  Certbot deploy hook: ${CERTBOT_DEPLOY_HOOK}"
  echo
  echo "Check:"
  echo "  nginx -t"
  echo "  systemctl status nginx"
  echo "  systemctl status certbot.timer"
  echo "  certbot renew --dry-run"
  echo "  ufw status verbose"
  echo "  ss -lntp | egrep ':443|:${PANEL_PORT}|:${SUB_PORT}|:${WS_PORT}|:${GRPC_PORT}|:${XHTTP_PORT}'"
}

generate_uuid() {
  if [[ -r /proc/sys/kernel/random/uuid ]]; then
    cat /proc/sys/kernel/random/uuid
  elif command -v uuidgen >/dev/null 2>&1; then
    uuidgen | tr '[:upper:]' '[:lower:]'
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c 'import uuid; print(uuid.uuid4())'
  else
    die "No UUID generator available (need /proc/sys/kernel/random/uuid, uuidgen, or python3)."
  fi
}

detect_country_flag() {
  local country_code=""

  if [[ -n "$VPS_COUNTRY_CODE" ]]; then
    country_code="${VPS_COUNTRY_CODE^^}"
    [[ "$country_code" =~ ^[A-Z]{2}$ ]] ||
      die "VPS_COUNTRY_CODE must be a two-letter ISO country code (for example, EE)."
  else
    country_code="$(curl -fsSL --max-time 5 https://ipapi.co/country/ 2>/dev/null || true)"

    # Fallback APIs if primary fails or returns non-country response
    if [[ ! "$country_code" =~ ^[A-Z]{2}$ ]]; then
      country_code="$(curl -fsSL --max-time 5 https://ifconfig.co/country-iso 2>/dev/null || true)"
    fi
    if [[ ! "$country_code" =~ ^[A-Z]{2}$ ]]; then
      country_code="$(curl -fsSL --max-time 5 http://ip-api.com/line/?fields=countryCode 2>/dev/null || true)"
    fi
  fi

  if [[ "$country_code" =~ ^[A-Z]{2}$ ]]; then
    # Convert 2-letter country code to regional indicator emoji.
    # A=0x1F1E6, B=0x1F1E7, ... Z=0x1F1FF
    local c1 c2
    c1=$(printf '%x' $(( $(printf '%d' "'${country_code:0:1}") - 65 + 0x1F1E6 )))
    c2=$(printf '%x' $(( $(printf '%d' "'${country_code:1:1}") - 65 + 0x1F1E6 )))
    # shellcheck disable=SC2059
    printf "\\U${c1}\\U${c2}"
  else
    printf '🌐'
  fi
}

install_3xui_and_inbounds() {
  local script_dir installer_out key value installer_script
  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

  # INSTALL_3XUI_SCRIPT allows tests to stub the installer without touching
  # the real file. Not meant to be set outside of tests.
  installer_script="${SETUP_3X_UI_SCRIPT:-${INSTALL_3XUI_SCRIPT:-${script_dir}/setup-3x-ui.sh}}"

  [[ -x "$installer_script" ]] ||
    die "setup-3x-ui.sh not found next to setup.sh (expected ${installer_script})."

  echo
  echo "=== Installing 3x-ui and configuring inbounds ==="
  echo "(3x-ui is the source of truth for its own username/password/port/path;"
  echo " they are generated by its installer, not dictated by this script.)"

  installer_out="$(
    PANEL_PORT="$PANEL_PORT" \
    WS_PORT="$WS_PORT" \
    WS_PATH="$WS_PATH" \
    GRPC_PORT="$GRPC_PORT" \
    GRPC_SERVICE="$GRPC_SERVICE" \
    XHTTP_PORT="$XHTTP_PORT" \
    XHTTP_PATH="$XHTTP_PATH" \
    SUB_PORT="$SUB_PORT" \
    SUB_PATH="$SUB_PATH" \
    SUB_DOMAIN="${PANEL_SUBDOMAIN}.${BASE_DOMAIN}" \
    VLESS_DOMAIN="${VLESS_SUBDOMAIN}.${BASE_DOMAIN}" \
    CLIENT_UUID="$CLIENT_UUID" \
    CLIENT_SUB_ID="$CLIENT_SUB_ID" \
    INBOUND_REMARK_WS="${INBOUND_REMARK_WS:-}" \
    INBOUND_REMARK_GRPC="${INBOUND_REMARK_GRPC:-}" \
    INBOUND_REMARK_XHTTP="${INBOUND_REMARK_XHTTP:-}" \
    XUI_VERSION="${XUI_VERSION:-}" \
    "$installer_script"
  )" || die "setup-3x-ui.sh failed."

  while IFS='=' read -r key value; do
    case "$key" in
      PANEL_PORT) PANEL_PORT="$value" ;;
      PANEL_PATH) PANEL_PATH="$value" ;;
      XUI_USERNAME) XUI_USERNAME="$value" ;;
      XUI_PASSWORD) XUI_PASSWORD="$value" ;;
      CLIENT_UUID) CLIENT_UUID="$value" ;;
      CLIENT_SUB_ID) CLIENT_SUB_ID="$value" ;;
    esac
  done <<< "$installer_out"

  [[ -n "$PANEL_PORT" && -n "$PANEL_PATH" && -n "$XUI_USERNAME" && -n "$XUI_PASSWORD" && -n "$CLIENT_UUID" ]] ||
    die "setup-3x-ui.sh did not report PANEL_PORT/PANEL_PATH/XUI_USERNAME/XUI_PASSWORD/CLIENT_UUID."

  validate_panel_port

  save_config
}

anonymize_vps() {
  local script_dir anonymize_script
  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

  # HARDEN_HOST_SCRIPT allows tests to stub harden-host.sh without touching
  # the real file. Not meant to be set outside of tests.
  anonymize_script="${HARDEN_HOST_SCRIPT:-${ANONYMIZE_SCRIPT:-${script_dir}/harden-host.sh}}"

  if [[ ! -x "$anonymize_script" ]]; then
    echo "WARNING: harden-host.sh not found next to setup.sh (expected ${anonymize_script}); skipping host hardening." >&2
    return
  fi

  echo
  echo "=== Hardening host (clock sync, DNS, sysctl, ICMP, TTL, banners) ==="
  "$anonymize_script" || echo "WARNING: harden-host.sh reported an error; continuing (this is not fatal to the proxy setup)." >&2
}

print_client_links() {
  echo
  echo "=== 3x-ui panel credentials (generated by the 3x-ui installer) ==="
  echo "  Username: ${XUI_USERNAME}"
  echo "  Password: ${XUI_PASSWORD}"
  echo "  URL:      https://${PANEL_SUBDOMAIN}.${BASE_DOMAIN}${PANEL_PATH}/"
  echo
  echo "=== Client VLESS URIs (ready to import into your client app) ==="
  echo "vless://${CLIENT_UUID}@${VLESS_SUBDOMAIN}.${BASE_DOMAIN}:443?type=ws&security=tls&path=$(printf '%s' "$WS_PATH" | sed 's#/#%2F#g')&host=${VLESS_SUBDOMAIN}.${BASE_DOMAIN}#${INBOUND_REMARK_WS}"
  echo "vless://${CLIENT_UUID}@${VLESS_SUBDOMAIN}.${BASE_DOMAIN}:443?type=grpc&security=tls&serviceName=${GRPC_SERVICE}&mode=gun&host=${VLESS_SUBDOMAIN}.${BASE_DOMAIN}#${INBOUND_REMARK_GRPC}"
  echo "vless://${CLIENT_UUID}@${VLESS_SUBDOMAIN}.${BASE_DOMAIN}:443?type=xhttp&security=tls&path=$(printf '%s' "$XHTTP_PATH" | sed 's#/#%2F#g')&mode=packet-up&host=${VLESS_SUBDOMAIN}.${BASE_DOMAIN}#${INBOUND_REMARK_XHTTP}"
}

verify_deployment() {
  local panel_domain="${PANEL_SUBDOMAIN}.${BASE_DOMAIN}"
  local vless_domain="${VLESS_SUBDOMAIN}.${BASE_DOMAIN}"
  local all_ok=true

  echo
  echo "=== Post-configuration verification ==="
  echo
  echo "Checking local listeners..."

  for check in "Panel:$PANEL_PORT" "Subscription:$SUB_PORT" "WebSocket:$WS_PORT" "gRPC:$GRPC_PORT" "XHTTP:$XHTTP_PORT"; do
    local check_name="${check%%:*}"
    local check_port="${check#*:}"

    if port_is_listening "$check_port"; then
      echo "  [OK]   ${check_name} is listening on 127.0.0.1:${check_port}"
    else
      echo "  [FAIL] ${check_name} is NOT listening on 127.0.0.1:${check_port}"
      all_ok=false
    fi
  done

  echo
  echo "Checking public HTTPS endpoints..."

  if command -v curl >/dev/null 2>&1; then
    local panel_status
    panel_status="$(curl -sk -o /dev/null -w '%{http_code}' --max-time 10 "https://${panel_domain}${PANEL_PATH}/" || echo "000")"

    if [[ "$panel_status" =~ ^(2|3)[0-9][0-9]$ ]]; then
      echo "  [OK]   https://${panel_domain}${PANEL_PATH}/ responded with HTTP ${panel_status}"
    else
      echo "  [FAIL] https://${panel_domain}${PANEL_PATH}/ responded with HTTP ${panel_status} (or was unreachable)"
      all_ok=false
    fi

    local vless_status
    vless_status="$(curl -sk -o /dev/null -w '%{http_code}' --max-time 10 "https://${vless_domain}/" || echo "000")"

    if [[ "$vless_status" =~ ^[0-9][0-9][0-9]$ && "$vless_status" != "000" ]]; then
      echo "  [OK]   TLS handshake to https://${vless_domain}/ succeeded (HTTP ${vless_status}, 404 is expected here)"
    else
      echo "  [FAIL] Could not complete a TLS handshake to https://${vless_domain}/"
      all_ok=false
    fi
  else
    echo "  [SKIP] curl not available for HTTPS checks."
  fi

  echo

  if [[ "$all_ok" == true ]]; then
    echo "All checks passed."
  else
    echo "Some checks failed. Verify your 3x-ui/Xray configuration matches the ports/paths above,"
    echo "then re-run the checks manually:"
    echo "  ss -lntp | egrep ':${PANEL_PORT}|:${SUB_PORT}|:${WS_PORT}|:${GRPC_PORT}|:${XHTTP_PORT}'"
    echo "  curl -vk https://${panel_domain}${PANEL_PATH}/"
    echo "  curl -vk https://${vless_domain}/"
  fi
}

uninstall_all() {
  local script_dir installer_script anonymize_script answer
  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
  installer_script="${SETUP_3X_UI_SCRIPT:-${INSTALL_3XUI_SCRIPT:-${script_dir}/setup-3x-ui.sh}}"
  anonymize_script="${HARDEN_HOST_SCRIPT:-${ANONYMIZE_SCRIPT:-${script_dir}/harden-host.sh}}"
  DELETE_CERT="${DELETE_CERT:-false}"

  require_root
  load_config

  echo "=== Uninstalling 3x-ui-cf-setup ==="
  echo "This removes: the Nginx site/Cloudflare-real-IP config, the Certbot"
  echo "deploy hook, the Cloudflare API token file, the UFW rules this script"
  echo "added, 3x-ui itself (service, binary, /etc/x-ui, /usr/local/x-ui), and"
  echo "this script's saved config/state files."
  echo
  echo "The Let's Encrypt certificate for '${BASE_DOMAIN:-<unknown -- none configured>}'"
  echo "is KEPT by default (Let's Encrypt rate-limits reissuance to 5 certs per"
  echo "exact domain set per 7 days -- deleting it needlessly on every"
  echo "uninstall/reinstall cycle burns that quota). Pass --delete-cert to also"
  echo "remove it."
  echo
  read -r -p "Continue? [y/N]: " answer

  case "$answer" in
    y|Y|yes|YES) ;;
    *) echo "Cancelled."; exit 0 ;;
  esac

  echo
  echo "--- Nginx ---"
  rm -f "$NGINX_SITE_ENABLED" "$NGINX_SITE" "$CF_REAL_IP_CONF" "$FALLBACK_HTML_DEST"
  if command -v nginx >/dev/null 2>&1; then
    nginx -t >/dev/null 2>&1 && (systemctl reload nginx || systemctl restart nginx) || true
  fi

  echo "--- Certbot ---"
  rm -f "$CERTBOT_DEPLOY_HOOK"
  if [[ "$DELETE_CERT" == true ]] && [[ -n "${BASE_DOMAIN:-}" ]] && command -v certbot >/dev/null 2>&1; then
    echo "Deleting certificate for ${BASE_DOMAIN} (--delete-cert was passed)..."
    certbot delete --cert-name "$BASE_DOMAIN" --non-interactive >/dev/null 2>&1 || true
  else
    echo "Keeping existing certificate for ${BASE_DOMAIN:-<unknown>} (pass --delete-cert to remove it)."
  fi
  rm -f "$CF_CREDENTIALS"

  echo "--- UFW ---"
  if command -v ufw >/dev/null 2>&1; then
    # SSH is never touched -- this script never added an SSH rule, so it
    # never removes one either (see configure_ufw).
    # Remove the 443 allow rule this script owns, plus any leftover
    # per-range Cloudflare-only allow rules from installs predating direct-
    # connection inbounds (VLESS+Reality, NaiveProxy).
    ufw delete allow 443/tcp >/dev/null 2>&1 || true
    if [[ -f "$CF_IP_STATE_FILE" ]]; then
      while IFS= read -r cf_range; do
        [[ -n "$cf_range" ]] || continue
        ufw delete allow from "$cf_range" to any port 443 proto tcp >/dev/null 2>&1 || true
      done < "$CF_IP_STATE_FILE"
    fi
    ufw delete deny 443/tcp >/dev/null 2>&1 || true
    ufw delete deny 80/tcp >/dev/null 2>&1 || true
    for p in "${PANEL_PORT:-}" "${SUB_PORT:-}" "${WS_PORT:-}" "${GRPC_PORT:-}" "${XHTTP_PORT:-}"; do
      [[ -n "$p" ]] && ufw delete deny "${p}/tcp" >/dev/null 2>&1 || true
    done
    ufw reload >/dev/null 2>&1 || true
  fi

  echo "--- 3x-ui ---"
  if [[ -x "$installer_script" ]]; then
    "$installer_script" --uninstall || echo "WARNING: setup-3x-ui.sh --uninstall reported an error; check manually." >&2
  else
    echo "WARNING: setup-3x-ui.sh not found next to setup.sh (expected ${installer_script}); skipping 3x-ui removal." >&2
  fi

  echo "--- VPS anonymization ---"
  if [[ -x "$anonymize_script" ]]; then
    "$anonymize_script" --uninstall || echo "WARNING: harden-host.sh --uninstall reported an error; check manually." >&2
  else
    echo "WARNING: harden-host.sh not found next to setup.sh (expected ${anonymize_script}); skipping host-hardening revert." >&2
  fi

  echo "--- Local state ---"
  rm -f "$STATE_FILE" "$CF_IP_STATE_FILE" "$CONFIG_FILE"

  echo
  echo "Done. Uninstall complete."
}

main() {
  if [[ "${1:-}" == "--uninstall" ]]; then
    if [[ "${2:-}" == "--delete-cert" ]]; then
      DELETE_CERT=true
    fi
    uninstall_all
    return
  fi

  require_root
  load_config
  collect_input
  save_config

  CERT_DIR="/etc/letsencrypt/live/${BASE_DOMAIN}"

  confirm_configuration

  VPS_FLAG="$(detect_country_flag)"
  INBOUND_REMARK_WS="${VPS_FLAG} WebSocket-CDN"
  INBOUND_REMARK_GRPC="${VPS_FLAG} gRPC-CDN"
  INBOUND_REMARK_XHTTP="${VPS_FLAG} XHTTP-CDN"

  install_packages
  anonymize_vps
  install_3xui_and_inbounds
  write_cloudflare_credentials
  issue_certificate
  install_certbot_hook
  write_cloudflare_real_ip_config
  write_nginx_config
  configure_ufw
  print_summary
  save_config
  print_client_links
  verify_deployment
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
